name: qgrid-environment
channels:
  - conda-forge
  - defaults
dependencies:
  - jupyterlab
  - qgrid  
  - matplotlib
  - pandas=0.25.3
  - numpy
  - scikit-learn
  - scikit-image
  - scipy
  - seaborn
